project_id = "twqgpswsgethayrgqtjz"

[functions.ai-chat]
verify_jwt = false

[functions.mains-question]
verify_jwt = false

[functions.map-questions]
verify_jwt = false

[functions.pyq-analysis]
verify_jwt = false

[functions.mind-map-generator]
verify_jwt = false

[functions.daily-intel-report]
verify_jwt = false
